version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: |
          yum install epel-release -y
          yum install ansible -y
          yum install openssh -y 
          yum install unzip -y
          ssh-keygen -t rsa -f $HOME/.ssh/id_rsa_ansible -q -P ""
          cat ~/.ssh/id_rsa_ansible.pub >> ~/.ssh/authorized_keys
          ansible-playbook deploy_popcorntime.yaml
          ansible-playbook uninstall_popcorntime.yaml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
